-- 코드를 작성해주세요
SELECT
    E1.ID
FROM
    ECOLI_DATA AS E1
    LEFT JOIN ECOLI_DATA AS E2
    ON E1.PARENT_ID = E2.ID
    LEFT JOIN ECOLI_DATA AS E3
    ON E2.PARENT_ID = E3.ID
    LEFT JOIN ECOLI_DATA AS E4
    ON E3.PARENT_ID = E4.ID
WHERE
    E1.ID IS NOT NULL AND
    E2.ID IS NOT NULL AND
    E3.ID IS NOT NULL AND
    E4.ID IS NULL
    
ORDER BY
    E1.ID ASC