-- 코드를 작성해주세요
SELECT
    I.ITEM_ID
    , I.ITEM_NAME
    , I.RARITY
FROM
    ITEM_INFO AS I
    LEFT JOIN ITEM_TREE AS IT
    ON I.ITEM_ID = IT.PARENT_ITEM_ID
WHERE
    IT.PARENT_ITEM_ID IS NULL
GROUP BY
    I.ITEM_ID
ORDER BY
    I.ITEM_ID DESC