-- 코드를 입력하세요
WITH OPT AS (SELECT
    *
FROM
    CAR_RENTAL_COMPANY_CAR AS T1
WHERE
    T1.OPTIONS LIKE '%열선시트%'
    OR T1.OPTIONS LIKE '%통풍시트%'
    OR T1.OPTIONS LIKE '%가죽시트%')
    
SELECT
    T1.CAR_TYPE
    ,COUNT(T1.CAR_TYPE) AS CARS
FROM
    CAR_RENTAL_COMPANY_CAR AS T1
    JOIN OPT AS T2
    ON T1.CAR_ID = T2.CAR_ID
GROUP BY
    T1.CAR_TYPE
ORDER BY
    T1.CAR_TYPE ASC

    