-- 코드를 입력하세요
WITH RENT AS (
SELECT
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT
    T1.CAR_ID
    , (CASE
       WHEN T2.CAR_ID IS NULL
       THEN'대여 가능'
       ELSE '대여중'
      END) AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
    LEFT JOIN RENT AS T2
    ON T1.CAR_ID = T2.CAR_ID
GROUP BY
    T1.CAR_ID
ORDER BY
    T1.CAR_ID DESC

