-- 코드를 입력하세요
SELECT
    T1.PRODUCT_ID
    , T1.PRODUCT_NAME
    , (T1.PRICE * SUM(T2.AMOUNT)) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS T1
    JOIN FOOD_ORDER AS T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE
    T2.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY    
    T1.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC
    , T1.PRODUCT_ID ASC
# SELECT
#     PRODUCT_ID
#     , SUM(AMOUNT)
# FROM
#     FOOD_ORDER
# WHERE
#     PRODUCE_DATE LIKE '%2022-05%'
# GROUP BY    
#     PRODUCT_ID
    