-- 코드를 입력하세요
SELECT
    T1.FLAVOR
    # , T1.TOTAL_ORDER + SUM(T2.TOTAL_ORDER) AS TOTAL
FROM
    FIRST_HALF AS T1
    JOIN JULY AS T2
    ON T1.FLAVOR = T2.FLAVOR
GROUP BY
    T1.FLAVOR
ORDER BY
    T1.TOTAL_ORDER + SUM(T2.TOTAL_ORDER) DESC
LIMIT
    3

    
    
    
    