-- 코드를 작성해주세요
WITH FRONT_SKILL AS (
    SELECT
        SUM(CODE) AS CODE
    FROM
        SKILLCODES
    WHERE
        CATEGORY = 'Front End'
)

SELECT
    T1.ID
    , T1.EMAIL
    , T1.FIRST_NAME
    , T1.LAST_NAME
FROM
    DEVELOPERS AS T1
WHERE
    T1.SKILL_CODE & (SELECT CODE FROM FRONT_SKILL) != 0
ORDER BY
    T1.ID