-- 코드를 입력하세요
WITH BOARD AS (SELECT
    WRITER_ID
    , SUM(PRICE) AS TOTAL
FROM
    USED_GOODS_BOARD
WHERE
    STATUS = 'DONE'
GROUP BY
    WRITER_ID)
    

SELECT
    T1.USER_ID
    , T1.NICKNAME
    , T2.TOTAL AS TOTAL_SALES
FROM
    USED_GOODS_USER AS T1
    JOIN BOARD AS T2
    ON T1.USER_ID = T2.WRITER_ID
WHERE
    T2.TOTAL >= 700000
ORDER BY
    T2.TOTAL ASC
    