-- 코드를 입력하세요
SELECT
    T1.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR AS T1
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
    ON T1.CAR_ID = T2.CAR_ID
WHERE
    T2.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
    AND T1.CAR_TYPE = '세단'
GROUP BY
    T1.CAR_ID
ORDER BY
    T1.CAR_ID DESC