-- 코드를 입력하세요
SELECT
    B.BOOK_ID
    , DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d')
FROM
    BOOK AS B
WHERE
    B.PUBLISHED_DATE LIKE '%2021-%' AND
    B.CATEGORY = '인문'
ORDER BY
    B.PUBLISHED_DATE ASC